{"name": "test_add[get_datas_add0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pratice_demo.pratice_calculator_advanced.test_calc_new.TestCalculator object at 0x0000024314E8D4C0>\nget_calc = <pratice_demo.pratice_calculator_advanced.demo.calc.Calculator object at 0x0000024314E8D550>, get_datas_add = [999999999.9, 1, 10000000000.9]\n\n    @allure.story(\"计算器的加法测试\")\n    @pytest.mark.run(order=1)\n    def test_add(self, get_calc, get_datas_add):\n        # 假设最大能输入999999999\n        if get_datas_add[0] > 999999999 or get_datas_add[1] > 999999999:\n            print(\"超出最大数值999999999，不允许输出\")\n>           assert False\nE           assert False\n\ntest_calc_new.py:71: AssertionError"}, "attachments": [{"name": "stdout", "source": "3b28d78c-24d7-47e8-854c-526623d5f48c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_add", "value": "[999999999.9, 1, 10000000000.9]"}], "start": 1612345709070, "stop": 1612345709071, "uuid": "8d89abc7-4bab-45ad-9fa9-2dfb9416b957", "historyId": "aecad3b7e8d3158f3cda373dbaac3ce1", "testCaseId": "3d63d6b6e535a2d30dc56b2e66da2d0a", "fullName": "test_calc_new.TestCalculator#test_add", "labels": [{"name": "feature", "value": "测试计算器"}, {"name": "story", "value": "计算器的加法测试"}, {"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "10164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}